name = "zero-cache"
main = "./out/tool/miniflare-environment.js"

workers_dev = true

compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "runnerDO", class_name = "ServiceRunnerDO" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ServiceRunnerDO"]

