name: Replicache Bundle Size

on:
  push:
    branches: [main]
    paths:
      - 'packages/replicache/**'

jobs:
  bundle-size:
    name: Bundle Sizes Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run --workspace=replicache build-bundle-sizes
      - run: brotli packages/replicache/out/*

      # Builds bundles then measures bundles sizes and stores them to a file
      - name: Measure bundles
        run: node tool/bundle-sizes.js --bundles replicache.mjs replicache.mjs.br replicache.min.mjs replicache.min.mjs.br | tee bundle-sizes.json
        working-directory: packages/replicache

      # Run `github-action-benchmark` action
      - name: Store bundle size
        uses: rhysd/github-action-benchmark@v1
        with:
          name: 'Bundle Sizes'
          tool: 'customSmallerIsBetter'
          output-file-path: packages/replicache/bundle-sizes.json
          fail-on-alert: true
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          benchmark-data-dir-path: bundle-sizes
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
